hunter_config(LAPACK
  VERSION ${HUNTER_LAPACK_VERSION}
  CMAKE_ARGS BUILD_SHARED_LIBS=ON
  # CMAKE_POSITION_INDEPENDENT_CODE=ON
)
hunter_config(ARPACK
  VERSION ${HUNTER_ARPACK_VERSION}
  CMAKE_ARGS ENABLE_STATIC=OFF
)
hunter_config(OpenBLAS
  VERSION ${HUNTER_OpenBLAS_VERSION}
  CMAKE_ARGS BUILD_SHARED_LIBS=ON
)
